#!/usr/bin/env node
/**
 * Analyze actual data to understand model discrepancy
 */

const API_BASE = 'http://localhost:3000';
const API_KEY = 'sk_dash_7f3k9m2x5p8q1n4v6b0c';

async function main() {
  console.log('='.repeat(60));
  console.log('DATA ANALYSIS');
  console.log('='.repeat(60));

  // Fetch all available data
  const headers = {
    'Content-Type': 'application/json',
    'X-API-Key': API_KEY,
  };

  const [backtestRes, forecastRes, mainRes] = await Promise.all([
    fetch(`${API_BASE}/dashboard/backtest`, { headers }),
    fetch(`${API_BASE}/dashboard/forecast`, { headers }),
    fetch(`${API_BASE}/dashboard/main`, { headers }),
  ]);

  const backtest = await backtestRes.json();
  const forecast = await forecastRes.json();
  const main = await mainRes.json();

  console.log('\n=== BACKTEST DATA ===');
  console.log(`Historical months: ${backtest.historical?.length}`);

  // Analyze last 6 months
  console.log('\nLast 6 months:');
  const last6 = backtest.historical?.slice(-6) || [];
  last6.forEach(m => {
    const revPerSub = m.revenue / m.subscribers;
    console.log(`  ${m.month}: revenue=$${(m.revenue/1000).toFixed(1)}k, subs=${m.subscribers}, rev/sub=$${revPerSub.toFixed(2)}`);
  });

  // Average revenue per subscriber
  const avgRevPerSub = last6.reduce((s, m) => s + m.revenue / m.subscribers, 0) / last6.length;
  console.log(`\n  Average revenue per subscriber: $${avgRevPerSub.toFixed(2)}`);

  console.log('\n=== FORECAST ENDPOINT ===');
  console.log(`Weekly churn: ${forecast.weeklyChurn}%`);
  console.log(`Yearly churn: ${forecast.yearlyChurn}%`);
  console.log(`Daily ARPPU: $${forecast.arppu}`);
  console.log(`Monthly retention: ${forecast.monthlyRetention}%`);

  console.log('\n=== MAIN DASHBOARD ===');
  console.log('Monthly ARPU:', main.monthly?.arpu);
  console.log('Last month revenue:', main.monthly?.revenue);

  // Calculate what ARPPU would explain the revenue
  console.log('\n=== ARPPU ANALYSIS ===');
  console.log('If revenue = subscribers × ARPPU × period:');

  // Get cumulative active subs using current model
  // Let me estimate what ARPPU fits the data
  const recentMonths = backtest.historical?.slice(-12) || [];

  // Simple model: revenue = active_subs × monthly_arppu
  // But we don't have active_subs directly...

  // Let's calculate implied ARPPU per NEW subscriber
  // This is the immediate revenue generated by a new subscriber
  console.log('\nImplied revenue per NEW subscriber (not LTV):');
  recentMonths.forEach(m => {
    // Revenue divided by new subs
    // But this isn't right because revenue includes old subs too
  });

  // Better: calculate what the model SHOULD produce vs what it does
  // My model uses: weekly $6.99 × 4.33 = $30.27/month for weekly
  // And: yearly $49.99/12 = $4.17/month for yearly

  // With 82% weekly, the blended monthly revenue per active sub is:
  // 0.82 × 30.27 + 0.18 × 4.17 = 24.82 + 0.75 = $25.57/month per active subscriber

  const weeklyMonthly = 6.99 * 4.33;
  const yearlyMonthly = 49.99 / 12;
  const blendedARPPU = 0.82 * weeklyMonthly + 0.18 * yearlyMonthly;
  console.log(`\nModel assumes blended ARPPU: $${blendedARPPU.toFixed(2)}/month`);
  console.log(`  Weekly: $${weeklyMonthly.toFixed(2)}/mo (82% share)`);
  console.log(`  Yearly: $${yearlyMonthly.toFixed(2)}/mo (18% share)`);

  // What ARPPU would fit actual data?
  // Let's reverse-engineer from Feb 2026: $110k revenue
  // If my model predicts $78k with 82% weekly share, what's the actual ARPPU?
  // $110k / $78k = 1.41x multiplier needed
  console.log(`\nTo match actuals, ARPPU should be: $${(blendedARPPU * 110.2 / 78.1).toFixed(2)}/month`);
  console.log(`This is ${(110.2 / 78.1 * 100 - 100).toFixed(0)}% higher than modeled`);

  // Check if weekly share might be wrong
  console.log('\n=== WEEKLY SHARE SENSITIVITY ===');
  for (let share = 50; share <= 90; share += 10) {
    const blend = (share/100) * weeklyMonthly + ((100-share)/100) * yearlyMonthly;
    console.log(`  ${share}% weekly: $${blend.toFixed(2)}/mo per active sub`);
  }

  // The issue might be that PRICES are higher than assumed
  console.log('\n=== PRICE SENSITIVITY ===');
  // App Store prices in USD
  const possibleWeeklyPrices = [4.99, 6.99, 9.99, 12.99, 14.99];
  const possibleYearlyPrices = [29.99, 39.99, 49.99, 59.99, 69.99, 79.99];

  console.log('If weekly price is different (82% weekly share):');
  possibleWeeklyPrices.forEach(wp => {
    const blend = 0.82 * wp * 4.33 + 0.18 * 49.99/12;
    console.log(`  $${wp}/week → $${blend.toFixed(2)}/mo blended`);
  });

  console.log('\nIf yearly price is different (18% yearly share):');
  possibleYearlyPrices.forEach(yp => {
    const blend = 0.82 * 6.99 * 4.33 + 0.18 * yp/12;
    console.log(`  $${yp}/year → $${blend.toFixed(2)}/mo blended`);
  });
}

main().catch(console.error);
